/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as InviteInvitationIdIndexRouteImport } from './routes/invite/$invitationId/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppTeamsTeamIdRouteRouteImport } from './routes/_app/teams/$teamId/route'
import { Route as AppTeamsTeamIdTasksIndexRouteImport } from './routes/_app/teams/$teamId/tasks/index'
import { Route as AppTeamsTeamIdStatutsIndexRouteImport } from './routes/_app/teams/$teamId/statuts/index'
import { Route as AppTeamsTeamIdProjectsIndexRouteImport } from './routes/_app/teams/$teamId/projects/index'
import { Route as AppTeamsTeamIdPeopleIndexRouteImport } from './routes/_app/teams/$teamId/people/index'
import { Route as AppTeamsTeamIdManagementIndexRouteImport } from './routes/_app/teams/$teamId/management/index'
import { Route as AppTeamsTeamIdIssuesIndexRouteImport } from './routes/_app/teams/$teamId/issues/index'
import { Route as AppTeamsTeamIdProjectsProjectIdIndexRouteImport } from './routes/_app/teams/$teamId/projects/$projectId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdIndexRoute = InviteInvitationIdIndexRouteImport.update({
  id: '/invite/$invitationId/',
  path: '/invite/$invitationId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamsTeamIdRouteRoute = AppTeamsTeamIdRouteRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamsTeamIdTasksIndexRoute =
  AppTeamsTeamIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdStatutsIndexRoute =
  AppTeamsTeamIdStatutsIndexRouteImport.update({
    id: '/statuts/',
    path: '/statuts/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdProjectsIndexRoute =
  AppTeamsTeamIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdPeopleIndexRoute =
  AppTeamsTeamIdPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdManagementIndexRoute =
  AppTeamsTeamIdManagementIndexRouteImport.update({
    id: '/management/',
    path: '/management/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdIssuesIndexRoute =
  AppTeamsTeamIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)
const AppTeamsTeamIdProjectsProjectIdIndexRoute =
  AppTeamsTeamIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppTeamsTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteRouteWithChildren
  '/teams/': typeof AppTeamsIndexRoute
  '/invite/$invitationId/': typeof InviteInvitationIdIndexRoute
  '/teams/$teamId/issues/': typeof AppTeamsTeamIdIssuesIndexRoute
  '/teams/$teamId/management/': typeof AppTeamsTeamIdManagementIndexRoute
  '/teams/$teamId/people/': typeof AppTeamsTeamIdPeopleIndexRoute
  '/teams/$teamId/projects/': typeof AppTeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/statuts/': typeof AppTeamsTeamIdStatutsIndexRoute
  '/teams/$teamId/tasks/': typeof AppTeamsTeamIdTasksIndexRoute
  '/teams/$teamId/projects/$projectId/': typeof AppTeamsTeamIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteRouteWithChildren
  '/teams': typeof AppTeamsIndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdIndexRoute
  '/teams/$teamId/issues': typeof AppTeamsTeamIdIssuesIndexRoute
  '/teams/$teamId/management': typeof AppTeamsTeamIdManagementIndexRoute
  '/teams/$teamId/people': typeof AppTeamsTeamIdPeopleIndexRoute
  '/teams/$teamId/projects': typeof AppTeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/statuts': typeof AppTeamsTeamIdStatutsIndexRoute
  '/teams/$teamId/tasks': typeof AppTeamsTeamIdTasksIndexRoute
  '/teams/$teamId/projects/$projectId': typeof AppTeamsTeamIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRouteRouteWithChildren
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/invite/$invitationId/': typeof InviteInvitationIdIndexRoute
  '/_app/teams/$teamId/issues/': typeof AppTeamsTeamIdIssuesIndexRoute
  '/_app/teams/$teamId/management/': typeof AppTeamsTeamIdManagementIndexRoute
  '/_app/teams/$teamId/people/': typeof AppTeamsTeamIdPeopleIndexRoute
  '/_app/teams/$teamId/projects/': typeof AppTeamsTeamIdProjectsIndexRoute
  '/_app/teams/$teamId/statuts/': typeof AppTeamsTeamIdStatutsIndexRoute
  '/_app/teams/$teamId/tasks/': typeof AppTeamsTeamIdTasksIndexRoute
  '/_app/teams/$teamId/projects/$projectId/': typeof AppTeamsTeamIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/teams/$teamId'
    | '/teams/'
    | '/invite/$invitationId/'
    | '/teams/$teamId/issues/'
    | '/teams/$teamId/management/'
    | '/teams/$teamId/people/'
    | '/teams/$teamId/projects/'
    | '/teams/$teamId/statuts/'
    | '/teams/$teamId/tasks/'
    | '/teams/$teamId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/teams/$teamId'
    | '/teams'
    | '/invite/$invitationId'
    | '/teams/$teamId/issues'
    | '/teams/$teamId/management'
    | '/teams/$teamId/people'
    | '/teams/$teamId/projects'
    | '/teams/$teamId/statuts'
    | '/teams/$teamId/tasks'
    | '/teams/$teamId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth/login'
    | '/_app/teams/$teamId'
    | '/_app/teams/'
    | '/invite/$invitationId/'
    | '/_app/teams/$teamId/issues/'
    | '/_app/teams/$teamId/management/'
    | '/_app/teams/$teamId/people/'
    | '/_app/teams/$teamId/projects/'
    | '/_app/teams/$teamId/statuts/'
    | '/_app/teams/$teamId/tasks/'
    | '/_app/teams/$teamId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  InviteInvitationIdIndexRoute: typeof InviteInvitationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId/': {
      id: '/invite/$invitationId/'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId/'
      preLoaderRoute: typeof InviteInvitationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/teams/$teamId/tasks/': {
      id: '/_app/teams/$teamId/tasks/'
      path: '/tasks'
      fullPath: '/teams/$teamId/tasks/'
      preLoaderRoute: typeof AppTeamsTeamIdTasksIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/statuts/': {
      id: '/_app/teams/$teamId/statuts/'
      path: '/statuts'
      fullPath: '/teams/$teamId/statuts/'
      preLoaderRoute: typeof AppTeamsTeamIdStatutsIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/projects/': {
      id: '/_app/teams/$teamId/projects/'
      path: '/projects'
      fullPath: '/teams/$teamId/projects/'
      preLoaderRoute: typeof AppTeamsTeamIdProjectsIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/people/': {
      id: '/_app/teams/$teamId/people/'
      path: '/people'
      fullPath: '/teams/$teamId/people/'
      preLoaderRoute: typeof AppTeamsTeamIdPeopleIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/management/': {
      id: '/_app/teams/$teamId/management/'
      path: '/management'
      fullPath: '/teams/$teamId/management/'
      preLoaderRoute: typeof AppTeamsTeamIdManagementIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/issues/': {
      id: '/_app/teams/$teamId/issues/'
      path: '/issues'
      fullPath: '/teams/$teamId/issues/'
      preLoaderRoute: typeof AppTeamsTeamIdIssuesIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
    '/_app/teams/$teamId/projects/$projectId/': {
      id: '/_app/teams/$teamId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/teams/$teamId/projects/$projectId/'
      preLoaderRoute: typeof AppTeamsTeamIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppTeamsTeamIdRouteRoute
    }
  }
}

interface AppTeamsTeamIdRouteRouteChildren {
  AppTeamsTeamIdIssuesIndexRoute: typeof AppTeamsTeamIdIssuesIndexRoute
  AppTeamsTeamIdManagementIndexRoute: typeof AppTeamsTeamIdManagementIndexRoute
  AppTeamsTeamIdPeopleIndexRoute: typeof AppTeamsTeamIdPeopleIndexRoute
  AppTeamsTeamIdProjectsIndexRoute: typeof AppTeamsTeamIdProjectsIndexRoute
  AppTeamsTeamIdStatutsIndexRoute: typeof AppTeamsTeamIdStatutsIndexRoute
  AppTeamsTeamIdTasksIndexRoute: typeof AppTeamsTeamIdTasksIndexRoute
  AppTeamsTeamIdProjectsProjectIdIndexRoute: typeof AppTeamsTeamIdProjectsProjectIdIndexRoute
}

const AppTeamsTeamIdRouteRouteChildren: AppTeamsTeamIdRouteRouteChildren = {
  AppTeamsTeamIdIssuesIndexRoute: AppTeamsTeamIdIssuesIndexRoute,
  AppTeamsTeamIdManagementIndexRoute: AppTeamsTeamIdManagementIndexRoute,
  AppTeamsTeamIdPeopleIndexRoute: AppTeamsTeamIdPeopleIndexRoute,
  AppTeamsTeamIdProjectsIndexRoute: AppTeamsTeamIdProjectsIndexRoute,
  AppTeamsTeamIdStatutsIndexRoute: AppTeamsTeamIdStatutsIndexRoute,
  AppTeamsTeamIdTasksIndexRoute: AppTeamsTeamIdTasksIndexRoute,
  AppTeamsTeamIdProjectsProjectIdIndexRoute:
    AppTeamsTeamIdProjectsProjectIdIndexRoute,
}

const AppTeamsTeamIdRouteRouteWithChildren =
  AppTeamsTeamIdRouteRoute._addFileChildren(AppTeamsTeamIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppTeamsTeamIdRouteRoute: typeof AppTeamsTeamIdRouteRouteWithChildren
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTeamsTeamIdRouteRoute: AppTeamsTeamIdRouteRouteWithChildren,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  InviteInvitationIdIndexRoute: InviteInvitationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
